### ISSUE TITLE
Toasty is offline

### ISSUE THREAD

**Issue by Milo123459** [Shamil-FD/ToastyXD#12]
@Shamil-FD care to share the logs? Toasty has been offline for a while now. DM me them on discord if preferable, we also have a bit of catching up to do.

**Comment by Milo123459** [comment]
@Shamil-FD can I have access to the DBH server?

**Comment by FC5570** [comment]
I'll try to ask dan once he's online to give me access to his server, but I'm not sure if Toasty is hosted on DBH
