### ISSUE TITLE
Toasty is offline

### ISSUE THREAD

**Issue by Cy1der** [Shamil-FD/ToastyXD#13]
Yeah that's it, Shamil can you start it back up again?

![image](https://user-images.githubusercontent.com/67352978/115551629-57a36280-a279-11eb-97d6-ab83ca3958d6.png)

**Comment by FC5570** [comment]
dbh is having issues, dan has been working for more than 6 hours to fix this issue, fuck cloudflare

**Comment by FC5570** [comment]
![image](https://user-images.githubusercontent.com/68158483/115596015-3e3ffc00-a2f5-11eb-920e-8d940c884544.png)
